package parser

import (
	"os"
	"path/filepath"
	"testing"
)

func TestParseCargoLock(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "Cargo.lock")

	content := `# This file is automatically @generated by Cargo.
# It is not intended for manual editing.
version = 4

[[package]]
name = "serde"
version = "1.0.193"
source = "registry+https://github.com/rust-lang/crates.io-index"

[[package]]
name = "tokio"
version = "1.35.0"
source = "registry+https://github.com/rust-lang/crates.io-index"
dependencies = [
 "bytes",
 "pin-project-lite",
]

[[package]]
name = "my-project"
version = "0.1.0"
`

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	deps, err := ParseCargoLock(path)
	if err != nil {
		t.Fatal(err)
	}

	if len(deps) != 3 {
		t.Fatalf("got %d deps, want 3", len(deps))
	}

	if deps[0].Name != "serde" || deps[0].Version != "1.0.193" {
		t.Errorf("deps[0] = %s@%s, want serde@1.0.193", deps[0].Name, deps[0].Version)
	}
	if deps[1].Name != "tokio" || deps[1].Version != "1.35.0" {
		t.Errorf("deps[1] = %s@%s, want tokio@1.35.0", deps[1].Name, deps[1].Version)
	}
	for _, d := range deps {
		if d.System != SystemCargo {
			t.Errorf("System = %q, want CARGO", d.System)
		}
	}
}

func TestParseCargoToml(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "Cargo.toml")

	content := `[package]
name = "my-project"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = "1.0.193"
tokio = { version = "1.35.0", features = ["full"] }
log = "0.4.20"

[dev-dependencies]
tempfile = "3.9.0"
`

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	deps, err := ParseCargoToml(path)
	if err != nil {
		t.Fatal(err)
	}

	if len(deps) != 4 {
		t.Fatalf("got %d deps, want 4", len(deps))
	}

	want := map[string]string{
		"serde":    "1.0.193",
		"tokio":    "1.35.0",
		"log":      "0.4.20",
		"tempfile": "3.9.0",
	}
	for _, d := range deps {
		if expected, ok := want[d.Name]; ok {
			if d.Version != expected {
				t.Errorf("%s version = %q, want %q", d.Name, d.Version, expected)
			}
		} else {
			t.Errorf("unexpected dep: %s", d.Name)
		}
	}
}

func TestParseCargoTomlSkipsRanges(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "Cargo.toml")

	content := `[dependencies]
serde = "^1.0"
tokio = "~1.35"
exact = "1.0.0"
`

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	deps, err := ParseCargoToml(path)
	if err != nil {
		t.Fatal(err)
	}

	if len(deps) != 1 {
		t.Fatalf("got %d deps, want 1 (only exact)", len(deps))
	}
	if deps[0].Name != "exact" {
		t.Errorf("Name = %q, want \"exact\"", deps[0].Name)
	}
}

func TestParseCargoLockEmpty(t *testing.T) {
	dir := t.TempDir()
	path := filepath.Join(dir, "Cargo.lock")

	content := `# This file is automatically @generated by Cargo.
version = 4
`

	if err := os.WriteFile(path, []byte(content), 0644); err != nil {
		t.Fatal(err)
	}

	deps, err := ParseCargoLock(path)
	if err != nil {
		t.Fatal(err)
	}

	if len(deps) != 0 {
		t.Errorf("got %d deps, want 0", len(deps))
	}
}
